#!/usr/bin/env lua
-- Headless unit tests for plugin/glimpse_scanner.lua (plain Lua, no
-- KOReader). Run via check.sh; expects builder/fixture_extracted/ to exist
-- (regenerated by make_fixture_epub.py).

local HERE = (arg[0] or "scanner_tests.lua"):match("^(.*)/[^/]*$") or "."
local scanner = dofile(HERE .. "/../plugin/glimpse_scanner.lua")
local references = dofile(HERE .. "/../plugin/glimpse_references.lua")
local FIXTURE = HERE .. "/fixture_extracted"

local n_pass, n_fail = 0, 0
local function check(cond, label, extra)
    if cond then
        n_pass = n_pass + 1
    else
        n_fail = n_fail + 1
        io.stderr:write("FAIL: " .. label .. (extra and (" — " .. tostring(extra)) or "") .. "\n")
    end
end
local function eq(got, want, label)
    check(got == want, label, string.format("want %s, got %s", tostring(want), tostring(got)))
end

-- ── publisher-provided references ──────────────────────────────────────────

do
    local function read_file(path)
        local f = io.open(FIXTURE .. "/" .. path, "rb")
        if not f then return nil end
        local d = f:read("*a")
        f:close()
        return d
    end
    local refs, err = references.scan(read_file)
    check(refs ~= nil, "reference scan succeeds", err)
    if refs then
        eq(#refs.references, 2, "reference count")
        eq(refs.references[1].kind, "characters", "characters detected")
        eq(refs.references[2].kind, "glossary", "glossary detected")
        local text = references.read_text(read_file, refs.references[1])
        check(text and text:find("Ada Rowan", 1, true), "reference text is read lazily")
    end
end

-- ── dimension sniffers (synthetic bytes) ────────────────────────────────────

local function le16b(n) return string.char(n % 256, math.floor(n / 256) % 256) end
local function le24b(n)
    return string.char(n % 256, math.floor(n / 256) % 256, math.floor(n / 65536) % 256)
end
local function le32b(n) return le24b(n) .. string.char(math.floor(n / 16777216) % 256) end

do
    local gif = "GIF89a" .. le16b(320) .. le16b(200) .. string.rep("\0", 8)
    local w, h, fmt = scanner.get_image_dimensions(gif)
    eq(w, 320, "gif width"); eq(h, 200, "gif height"); eq(fmt, "gif", "gif format")
end

do
    local vp8l = "RIFF" .. "\0\0\0\0" .. "WEBP" .. "VP8L" .. "\0\0\0\0"
        .. string.char(0x2F, 143, 193, 74, 0) .. string.rep("\0", 8)
    local w, h, fmt = scanner.get_image_dimensions(vp8l)
    eq(w, 400, "webp vp8l width"); eq(h, 300, "webp vp8l height"); eq(fmt, "webp", "webp format")
end

do
    local vp8x = "RIFF" .. "\0\0\0\0" .. "WEBP" .. "VP8X" .. "\0\0\0\0"
        .. "\0\0\0\0" .. le24b(639) .. le24b(479) .. string.rep("\0", 4)
    local w, h = scanner.get_image_dimensions(vp8x)
    eq(w, 640, "webp vp8x width"); eq(h, 480, "webp vp8x height")
end

do
    local bmp = "BM" .. string.rep("\0", 16) .. le32b(800) .. le32b(600) .. string.rep("\0", 8)
    local w, h, fmt = scanner.get_image_dimensions(bmp)
    eq(w, 800, "bmp width"); eq(h, 600, "bmp height"); eq(fmt, "bmp", "bmp format")
end

do
    local w, h, fmt = scanner.get_image_dimensions('<svg width="450pt" height="300pt">')
    eq(w, 600, "svg pt width"); eq(h, 400, "svg pt height"); eq(fmt, "svg", "svg format")
    w, h = scanner.get_image_dimensions('<?xml version="1.0"?><svg viewBox="0 0 1024 768"><rect/></svg>')
    eq(w, 1024, "svg viewBox width"); eq(h, 768, "svg viewBox height")
    w, h, fmt = scanner.get_image_dimensions('<svg width="100%" height="100%">')
    eq(w, nil, "svg percent width is nil"); eq(fmt, "svg", "svg percent still detected as svg")
end

do
    local w, h = scanner.get_image_dimensions("not an image at all")
    eq(w, nil, "garbage has no width"); eq(h, nil, "garbage has no height")
    eq(select(3, scanner.get_image_dimensions("")), nil, "empty data no format")
end

-- ── meaningful_text ─────────────────────────────────────────────────────────

eq(scanner.meaningful_text("The Greyhold family tree"), "The Greyhold family tree", "prose alt kept")
eq(scanner.meaningful_text("map01.png"), nil, "filename alt rejected")
eq(scanner.meaningful_text("Image 3"), nil, "generator boilerplate rejected")
eq(scanner.meaningful_text("img_12"), nil, "img_NN rejected")
eq(scanner.meaningful_text("  "), nil, "blank rejected")
eq(scanner.meaningful_text("Cover of the book"), nil, "cover-ish rejected")
eq(scanner.meaningful_text("1897"), nil, "bare number rejected")

-- ── extract_images ──────────────────────────────────────────────────────────

do
    local html = [[
<p>before</p>
<!-- <img src="ghost.png"/> -->
<figure>
  <IMG SRC='pics/one.png' alt="Fig &amp; caption test" width=300 height=200>
  <figcaption>The <b>first</b> figure</figcaption>
</figure>
<img src="data:image/png;base64,AAAA"/>
<img src="http://example.com/x.png"/>
<svg><image xlink:href="pics/two.svg"/></svg>
]]
    local occ = scanner.extract_images(html)
    eq(#occ, 2, "extract count (comments, data:, http skipped)")
    eq(occ[1].src, "pics/one.png", "uppercase/single-quote src")
    eq(occ[1].alt, "Fig & caption test", "entity-decoded alt")
    eq(occ[1].attr_w, 300, "unquoted width attr")
    eq(occ[1].attr_h, 200, "unquoted height attr")
    eq(occ[1].in_figure, true, "figure detection")
    eq(occ[1].figcaption, "The first figure", "figcaption text, tags stripped")
    eq(occ[2].src, "pics/two.svg", "svg image xlink:href")
    eq(occ[2].in_figure, false, "svg image outside figure")
end

-- ── parse_container ─────────────────────────────────────────────────────────

eq(scanner.parse_container(
    '<container><rootfiles><rootfile full-path="ops/pkg.opf" media-type="application/oebps-package+xml"/></rootfiles></container>'),
    "ops/pkg.opf", "container rootfile path")
eq(scanner.parse_container("<container/>"), nil, "container without rootfile")

-- ── full scan over the fixture ──────────────────────────────────────────────

local function read_file(path)
    local f = io.open(FIXTURE .. "/" .. path, "rb")
    if not f then return nil end
    local d = f:read("*a")
    f:close()
    return d
end

local scan, err = scanner.scan(read_file)
check(scan ~= nil, "fixture scan succeeds", err)

if scan then
    eq(#scan.images, 14, "image count")
    eq(scan.spine_count, 9, "spine count")
    eq(scan.cover_path, "OEBPS/images/cover.png", "cover path from OPF")

    local by = {}
    for _, im in ipairs(scan.images) do
        by[im.path:match("[^/]+$")] = im
    end

    check(by["cover.png"] and by["cover.png"].is_cover, "cover flagged")
    eq(by["cover.png"] and by["cover.png"].spine_index, 1, "cover spine index")

    eq(by["ornament.png"] and by["ornament.png"].files_count, 3, "ornament in 3 chapters")
    eq(by["icon.png"] and by["icon.png"].files_count, 1, "commented-out icon not counted")

    local map = by["map.png"]
    check(map, "map found")
    if map then
        eq(map.width, 1200, "map width from PNG header")
        eq(map.height, 900, "map height")
        eq(map.caption, "Map of the Realm & its borders", "figcaption wins, entities+tags handled")
        eq(map.in_figure, true, "map in figure")
        eq(map.spine_index, 3, "map spine index")
    end

    local tree = by["tree.jpg"]
    check(tree, "tree found")
    if tree then
        eq(tree.width, 800, "jpeg width from SOF0")
        eq(tree.height, 1000, "jpeg height")
        eq(tree.caption, "The Greyhold family tree", "alt used as caption")
        eq(tree.format, "jpeg", "jpeg format")
    end

    local east = by["east map.png"]
    check(east, "URL-encoded subdir path resolved")
    if east then
        eq(east.path, "OEBPS/images/old maps/east map.png", "decoded, normalized path")
        eq(east.width, 900, "east map width")
        eq(east.caption, "Map of the Eastern Marches", "title attr used as caption")
        eq(east.spine_index, 6, "east map spine index")
    end

    local svg = by["map.svg"]
    check(svg, "svg image found")
    if svg then
        eq(svg.format, "svg", "svg format")
        eq(svg.width, 900, "svg width")
        eq(svg.spine_index, 7, "svg spine index")
    end

    eq(by["divider.png"] and by["divider.png"].width, 1600, "divider width")
    eq(by["medium.png"] and by["medium.png"].caption, nil, "medium has no caption")

    -- ── filtering levels ────────────────────────────────────────────────────

    local function names(list)
        local t = {}
        for _, im in ipairs(list) do
            t[#t + 1] = im.path:match("[^/]+$")
        end
        table.sort(t)
        return table.concat(t, ",")
    end

    local inc, stats = scanner.filter(scan.images, "balanced")
    eq(names(inc), "east map.png,map.png,map.svg,tree.jpg", "balanced keeps the 4 reference images")
    eq(stats.excluded.cover, 1, "balanced excludes cover")
    eq(stats.excluded.repeated, 1, "balanced excludes repeated ornament")
    eq(stats.excluded.aspect, 1, "balanced excludes divider by aspect")
    eq(stats.excluded.small, 2, "balanced excludes icon + medium as small")
    eq(stats.excluded.series, 4, "balanced excludes the 4 chapter banners as series")
    eq(stats.excluded.frontmatter, 1, "balanced excludes uncaptioned title art")

    inc = scanner.filter(scan.images, "relaxed")
    eq(names(inc), "east map.png,map.png,map.svg,medium.png,tree.jpg", "relaxed adds medium")

    inc = scanner.filter(scan.images, "strict")
    eq(names(inc), "east map.png,map.png,map.svg,tree.jpg", "strict keeps the big four")

    inc, stats = scanner.filter(scan.images, "all")
    eq(#inc, 14, "'all' includes everything")
    eq(stats.included, 14, "'all' stats")

    -- per-image reasons (used by builder/analyze_epub.lua)
    local _, bstats = scanner.filter(scan.images, "balanced")
    eq(bstats.reasons["OEBPS/images/map.png"], "keep", "reasons: map kept")
    eq(bstats.reasons["OEBPS/images/cover.png"], "cover", "reasons: cover")
    eq(bstats.reasons["OEBPS/images/ornament.png"], "repeated", "reasons: ornament")
    eq(bstats.reasons["OEBPS/images/divider.png"], "aspect", "reasons: divider")
    eq(bstats.reasons["OEBPS/images/icon.png"], "small", "reasons: icon")
    eq(bstats.reasons["OEBPS/images/ban2.png"], "series", "reasons: banner series")
    eq(bstats.reasons["OEBPS/images/titleart.png"], "frontmatter", "reasons: title art")
end

-- ── filter edge cases (synthetic records) ───────────────────────────────────

do
    local function img(t)
        t.files_count = t.files_count or 1
        t.total_count = t.total_count or 1
        t.spine_index = t.spine_index or 1
        t.order = t.order or 1
        return t
    end

    -- caption relief: 220x160 is under balanced thresholds, but captioned
    -- images get halved thresholds
    local inc = scanner.filter({ img{ path = "a", width = 220, height = 160, caption = "A map" } }, "balanced")
    eq(#inc, 1, "caption relief admits smaller captioned image")
    inc = scanner.filter({ img{ path = "a", width = 220, height = 160 } }, "balanced")
    eq(#inc, 0, "same size uncaptioned is filtered")

    -- unknown dimensions: captioned included (except strict)
    inc = scanner.filter({ img{ path = "b", caption = "A chart" } }, "balanced")
    eq(#inc, 1, "captioned image without dimensions kept at balanced")
    inc = scanner.filter({ img{ path = "b", caption = "A chart" } }, "strict")
    eq(#inc, 0, "captioned image without dimensions dropped at strict")
    inc = scanner.filter({ img{ path = "b" } }, "relaxed")
    eq(#inc, 0, "uncaptioned image without dimensions dropped")

    -- big file squeezed into a tiny display slot is decoration
    inc = scanner.filter({ img{ path = "c", width = 1000, height = 800, attr_width = 40, attr_height = 32 } }, "balanced")
    eq(#inc, 0, "attr-shrunk image filtered")

    -- tall captioned family tree: ratio relief
    inc = scanner.filter({ img{ path = "d", width = 700, height = 4000, caption = "Family tree" } }, "balanced")
    eq(#inc, 1, "tall captioned tree kept (ratio relief)")
    inc = scanner.filter({ img{ path = "d", width = 700, height = 4000 } }, "balanced")
    eq(#inc, 0, "tall uncaptioned image dropped")
end

-- ── decorative captions and dimension series ───────────────────────────────

do
    check(scanner.decorative_caption("Chapter 1 Choose the Good"), "chapter alt is decorative")
    check(scanner.decorative_caption("Prologue"), "prologue is decorative")
    check(scanner.decorative_caption("Book Title, Educated, Subtitle, A Memoir"), "title-page alt is decorative")
    check(scanner.decorative_caption("Also by Rebecca Yarros"), "also-by is decorative")
    check(scanner.decorative_caption("A Note on the Text"), "a-note-on is decorative")
    check(scanner.decorative_caption("Penguin Random House Back Ad logo"), "publisher logo alt is decorative")
    check(not scanner.decorative_caption("Geological survey of the northern range"), "survey caption not decorative")
    check(not scanner.decorative_caption("Map of the Realm"), "map caption is not decorative")
    check(not scanner.decorative_caption("The Greyhold family tree"), "tree caption is not decorative")

    local function img(t)
        t.files_count = t.files_count or 1
        t.total_count = t.total_count or 1
        t.spine_index = t.spine_index or 10
        t.order = t.order or 1
        return t
    end
    -- 4 same-dims images with UNIQUE real captions: genuine figure series, kept
    local figs = {}
    for i = 1, 4 do
        figs[i] = img{ path = "f" .. i, width = 1000, height = 800, caption = "Figure " .. i }
    end
    local inc = scanner.filter(figs, "balanced")
    eq(#inc, 4, "same-dims figures with unique captions all kept")
    -- same, but captions repeat (part-opener cycle): all dropped
    local parts = {}
    for i = 1, 4 do
        parts[i] = img{ path = "p" .. i, width = 1242, height = 1900,
                        caption = (i % 2 == 0) and "ALICE" or "MARIA", in_figure = true }
    end
    inc = scanner.filter(parts, "balanced")
    eq(#inc, 0, "same-dims art with repeating captions dropped as series")
    -- heading alt earns no caption relief and no ratio relief
    inc = scanner.filter({ img{ path = "h", width = 700, height = 4000, caption = "Chapter Nine" } }, "balanced")
    eq(#inc, 0, "tall banner with chapter alt dropped")
    -- uncaptioned cover-shaped image at spine 2: front matter
    inc = scanner.filter({ img{ path = "t", width = 800, height = 1200, spine_index = 2 } }, "balanced")
    eq(#inc, 0, "uncaptioned portrait at spine 2 dropped as frontmatter")
    local _, fstats = scanner.filter({ img{ path = "t", width = 800, height = 1200, spine_index = 2 } }, "balanced")
    eq(fstats.reasons["t"], "frontmatter", "frontmatter reason")
    -- same image deeper in the book: kept
    inc = scanner.filter({ img{ path = "t", width = 800, height = 1200, spine_index = 9 } }, "balanced")
    eq(#inc, 1, "same portrait deeper in the book kept")
    -- captioned map at spine 2: kept (caption protects front matter)
    inc = scanner.filter({ img{ path = "m", width = 800, height = 1200, spine_index = 2, caption = "Map of the coast" } }, "balanced")
    eq(#inc, 1, "captioned portrait map at spine 2 kept")
end

do
    check(scanner.decorative_caption("Author\226\128\153s Note"), "curly-apostrophe Author's Note is decorative")
    check(scanner.decorative_caption("Creation Lake: A Novel, by Rachel Kushner. Scribner."), "novel-by alt is decorative")
    check(not scanner.decorative_caption("A map of the routes travelled by the novelist"), "map caption with 'novel' substring but no ' by ' pattern only dies when both present")
    check(scanner.decorative_name("OEBPS/images/author.jpg"), "author.jpg is chrome")
    check(scanner.decorative_name("images/RedTower_Logo_horz.png"), "logo filename is chrome")
    check(scanner.decorative_name("OEBPS/images/FourthWing-title1.png"), "titleN.ext is chrome")
    check(not scanner.decorative_name("OEBPS/images/Map3.jpg"), "Map3.jpg is not chrome")
    check(not scanner.decorative_name("images/subtitle.png"), "subtitle not caught by title pattern")

    local function img(t)
        t.files_count = t.files_count or 1
        t.total_count = t.total_count or 1
        t.spine_index = t.spine_index or 10
        t.order = t.order or 1
        return t
    end
    -- decorative caption is an outright exclusion even for big one-off images
    local inc, st = scanner.filter({ img{ path = "b", width = 1974, height = 506, caption = "Prologue" } }, "balanced")
    eq(#inc, 0, "big one-off banner with Prologue alt dropped")
    eq(st.reasons["b"], "decorative", "decorative reason for heading alt")
    -- uncaptioned chrome filename dropped; captioned same file kept
    inc = scanner.filter({ img{ path = "x/author.jpg", width = 434, height = 652, in_figure = true } }, "balanced")
    eq(#inc, 0, "uncaptioned author photo dropped")
    inc = scanner.filter({ img{ path = "x/author.jpg", width = 434, height = 652, caption = "The expedition team, 1911" } }, "balanced")
    eq(#inc, 1, "genuinely captioned image with chrome-ish name kept")
    -- series with one unique caption among repeats: whole group dropped
    local parts = {}
    for i = 1, 5 do
        parts[i] = img{ path = "p" .. i, width = 1242, height = 1900,
                        caption = (i == 3) and "LOTTIE: (D. ???)" or ((i % 2 == 0) and "ALICE" or "MARIA"),
                        in_figure = true }
    end
    inc = scanner.filter(parts, "balanced")
    eq(#inc, 0, "series with any repeating caption drops the whole group")

    -- numbered part-opener captions within a series count as no caption
    local openers = {}
    local titles = { "I The Man in the Tree", "II The Breach", "III Three Keys", "iv Hell and the Gentry", "V The Shadow" }
    for i = 1, 5 do
        openers[i] = img{ path = "o" .. i, width = 1421, height = 2462, caption = titles[i], in_figure = true }
    end
    inc = scanner.filter(openers, "balanced")
    eq(#inc, 0, "roman-numeral part openers dropped as series")
    -- but distinct prose captions in a same-dims series still survive
    local plates = {}
    for i = 1, 5 do
        plates[i] = img{ path = "q" .. i, width = 1421, height = 2462, caption = "The expedition at camp " .. string.rep("x", i), in_figure = true }
    end
    inc = scanner.filter(plates, "balanced")
    eq(#inc, 5, "prose-captioned plates in same-dims series kept")
end

-- chrome metadata: filename tokens, OPF guide roles, epub:type semantics
do
    check(scanner.decorative_name("OEBPS/images/King_9780385528856_epub_tp_r1.jpg"), "publisher _tp_ token is chrome")
    check(scanner.decorative_name("OEBPS/King_9780385528856_epub_cop_r1.htm"), "_cop_ doc is chrome")
    check(scanner.decorative_name("images/West_9780399590511_epub3_001_cvi.jpg"), "_cvi_ token is chrome")
    check(not scanner.decorative_name("images/temple-map.jpg"), "temple-map not caught by tp token")
    check(not scanner.decorative_name("images/data01.jpg"), "data01 not caught by ata token")
    check(not scanner.decorative_name("images/setup.png"), "setup not caught")

    check(scanner.chrome_role("title-page"), "guide title-page is chrome")
    check(scanner.chrome_role("copyright-page"), "guide copyright-page is chrome")
    check(not scanner.chrome_role("text"), "guide text is NOT chrome")
    check(not scanner.chrome_role(nil), "nil role is not chrome")

    eq(scanner.epub_type_role('<html><body epub:type="frontmatter titlepage"><img src="a.jpg"/></body>'),
       "titlepage", "epub:type titlepage sniffed")
    eq(scanner.epub_type_role('<html><body epub:type="bodymatter chapter">'), nil, "bodymatter is not chrome")

    local book = scanner.parse_opf([[<package><manifest>
<item href="tp.xhtml" id="tp" media-type="application/xhtml+xml"/>
</manifest><spine><itemref idref="tp"/></spine>
<guide>
<reference href="tp.xhtml" title="Title Page" type="title-page"/>
<reference href="start.xhtml" title="Start" type="text"/>
</guide></package>]], "OEBPS")
    eq(book.guide["OEBPS/tp.xhtml"], "title-page", "guide reference parsed and resolved")
    eq(book.guide["OEBPS/start.xhtml"], "text", "guide text reference parsed")

    local function img(t)
        t.files_count = t.files_count or 1
        t.total_count = t.total_count or 1
        t.spine_index = t.spine_index or 10
        t.order = t.order or 1
        return t
    end
    -- The Stand's case: big uncaptioned image, deep in the spine, _tp_ name
    local inc, st = scanner.filter({ img{ path = "OEBPS/images/King_epub_tp_r1.jpg", width = 448, height = 620, spine_index = 5 } }, "balanced")
    eq(#inc, 0, "interior title page image dropped by filename token")
    eq(st.reasons["OEBPS/images/King_epub_tp_r1.jpg"], "decorative", "tp reason decorative")
    -- generic image name, but the containing DOC is declared title-page
    inc = scanner.filter({ img{ path = "img/i001.jpg", width = 448, height = 620, spine_index = 5, doc_path = "text/x01.htm", doc_role = "title-page" } }, "balanced")
    eq(#inc, 0, "image in guide-declared title-page doc dropped")
    -- generic image name, containing doc has chrome filename
    inc = scanner.filter({ img{ path = "img/i001.jpg", width = 448, height = 620, spine_index = 5, doc_path = "OEBPS/King_epub_tp_r1.htm" } }, "balanced")
    eq(#inc, 0, "image in tp-named doc dropped")
    -- captioned image in the same doc survives (a real frontispiece map)
    inc = scanner.filter({ img{ path = "img/i001.jpg", width = 448, height = 620, spine_index = 5, doc_path = "text/x01.htm", doc_role = "title-page", caption = "Map of Boulder" } }, "balanced")
    eq(#inc, 1, "captioned image survives chrome doc role")
end

-- weak captions must not rescue chrome-named files
do
    eq(scanner.meaningful_text("[Image]"), nil, "[Image] boilerplate rejected")
    eq(scanner.meaningful_text("images"), nil, "images boilerplate rejected")
    eq(scanner.meaningful_text("Photo 12"), nil, "photo NN rejected")
    check(scanner.decorative_caption("Penguin Books"), "publisher caption decorative")
    check(scanner.decorative_caption("Penguin Random House UK"), "publisher UK caption decorative")
    check(scanner.decorative_caption("reactor magazine advertisement"), "advertisement caption decorative")
    check(not scanner.decorative_caption("Map of Penguin Island"), "penguin mid-caption not decorative")
    check(scanner.weak_caption("Hell Bent by Leigh Bardugo"), "title-by-author is weak")
    check(scanner.weak_caption(nil), "nil caption is weak")
    check(not scanner.weak_caption("Painting of the valley below Greyhold as seen by travellers arriving from the north"), "long prose caption is strong")
    check(not scanner.weak_caption("The Greyhold family tree"), "real caption is strong")

    local function img(t)
        t.files_count = t.files_count or 1
        t.total_count = t.total_count or 1
        t.spine_index = t.spine_index or 10
        t.order = t.order or 1
        return t
    end
    local inc, st = scanner.filter({ img{ path = "x/titlepage.jpg", width = 1500, height = 2400, caption = "Fugitive Telemetry by Martha Wells", in_figure = true } }, "strict")
    eq(#inc, 0, "title-by-author titlepage dropped even at strict")
    eq(st.reasons["x/titlepage.jpg"], "decorative", "titlepage reason")
    inc = scanner.filter({ img{ path = "x/endpaper1.jpg", width = 2291, height = 1730, caption = "Hell Bent by Leigh Bardugo", in_figure = true } }, "balanced")
    eq(#inc, 0, "endpaper with by-author caption dropped")
    inc = scanner.filter({ img{ path = "x/prhuklogo.jpg", width = 512, height = 150, caption = "Penguin Random House UK" } }, "relaxed")
    eq(#inc, 0, "publisher logo dropped at relaxed")
    -- strong caption still shields a chrome-ish name
    inc = scanner.filter({ img{ path = "x/author.jpg", width = 800, height = 600, caption = "The expedition team photographed at base camp" } }, "balanced")
    eq(#inc, 1, "strong caption still rescues chrome-named file")
    -- by-author caption on a NORMAL filename is untouched
    inc = scanner.filter({ img{ path = "x/plate04.jpg", width = 900, height = 700, caption = "The valley painted by John Constable" } }, "balanced")
    eq(#inc, 1, "by-author caption on normal filename kept")
end

-- figure-naming conventions as a positive signal
do
    check(scanner.figure_name("OEBPS/images/f0156-01.jpg"), "fNNNN-NN is a figure")
    check(scanner.figure_name("images/fig12.png"), "figN is a figure")
    check(scanner.figure_name("Figure_3_2.jpeg"), "figure_ is a figure")
    check(not scanner.figure_name("images/f.jpg"), "bare f is not")
    check(not scanner.figure_name("titlepage.jpg"), "titlepage is not a figure")
    check(not scanner.figure_name("West_epub3_005_r1.jpg"), "publisher art name is not a figure")

    local function img(t)
        t.files_count = t.files_count or 1
        t.total_count = t.total_count or 1
        t.spine_index = t.spine_index or 10
        t.order = t.order or 1
        return t
    end
    -- The Gene's case: smallish genuine figure, boilerplate "Images" alt
    -- (rejected at scan), rescued by its figure filename
    local inc = scanner.filter({ img{ path = "img/f0156-01.jpg", width = 330, height = 260 } }, "balanced")
    eq(#inc, 1, "figure-named small image gets caption relief")
    inc = scanner.filter({ img{ path = "img/photo77.jpg", width = 330, height = 260 } }, "balanced")
    eq(#inc, 0, "same size without figure name still filtered")
end

-- namespace-prefixed OPF (EPUBLib and friends emit <opf:item>, <opf:spine>)
do
    local opf = [[<opf:package xmlns:opf="http://www.idpf.org/2007/opf" version="2.0">
<opf:metadata><opf:meta content="cov" name="cover"/></opf:metadata>
<opf:manifest>
<opf:item href="images/cover.jpg" id="cov" media-type="image/jpeg"/>
<opf:item href="c1.xhtml" id="c1" media-type="application/xhtml+xml"/>
</opf:manifest>
<opf:spine><opf:itemref idref="c1"/></opf:spine>
</opf:package>]]
    local book = scanner.parse_opf(opf, "OEBPS")
    eq(#book.spine, 1, "ns-prefixed spine parsed")
    eq(book.spine[1] and book.spine[1].path, "OEBPS/c1.xhtml", "ns-prefixed itemref resolved")
    eq(book.cover_path, "OEBPS/images/cover.jpg", "ns-prefixed cover meta resolved")
end

-- ── summary ─────────────────────────────────────────────────────────────────

print(string.format("scanner_tests: %d passed, %d failed", n_pass, n_fail))
os.exit(n_fail == 0 and 0 or 1)
